---

# TODO: add filebeat version
- name: Ensure filebeat is installed
  win_chocolatey:
    name: filebeat
    state: present

- name: Enshire {{filebeat_config_dir}} exists
  win_file: path={{filebeat_config_dir}} state=directory

- name: Ensure main filebeat.yml is generated
  win_template:
    src: filebeat.yml.j2
    dest: C:/ProgramData/chocolatey/lib/filebeat/tools/filebeat-1.2.3-windows/filebeat.yml
  notify: filebeat restart

- name: Ensure filebeat_log.yml is generated
  win_copy:
    src: filebeat_log.yml
    dest: "{{filebeat_config_dir}}/filebeat_log.yml"
  notify: filebeat restart

- name: Ensure filebeat service is started
  win_service: name=filebeat start_mode=auto state=started
